# Site settings
title: My Oh My Oh My
email: Anthonylayese1@gmail.com
description: Hiya, I'm Myron and this is my work. <br />Curating sights and sounds for those that care to listen.
baseurl: # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Boston
state: MA
zip_code: 02115
country: United States of America
phone: 

icon: fa-diamond # Font Awesome class for your site's icon

# Social settings
facebook_url:
github_url: https://github.com/MLayese
gitlab_url: 
googleplus_url: 
instagram_url: https://www.instagram.com/myronlayese/
linkedin_url: https://www.linkedin.com/in/myron-anthony-layese-b4854b167/
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown

sass:
style: compressed
